version: "2"
services:
  cassandra-seed:
    image: cassandra:3.9
    ports:
      - 9042:9042

  cassandra-node:
    image: cassandra:3.9
    environment:
      - CASSANDRA_SEEDS=cassandra-seed

  sbt:
    image: 1science/sbt
    volumes:
      - .:/app
      - ~/.ivy2:/root/.ivy2
